unbind r
bind r source-file ~/.config/tmux/tmux.conf
set -g prefix C-a

set -g mouse on

bind-key x kill-pane # skip "kill-pane 1? (y/n)" prompt
set -g detach-on-destroy off  # don't exit from tmux when closing a session

set -g default-terminal "tmux-256color"
set-option -g status-position top

# --- Start windows at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# --- LazyVim-style Split Shortcuts ---

# Split vertically with '|' (Shift + \)
unbind %
bind | split-window -h -c "#{pane_current_path}"

# Split horizontally with '-'
unbind '"'
bind - split-window -v -c "#{pane_current_path}"

## --- Theme Setup (Catppuccin) ---
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

set -g @catppuccin_window_default_background "default"
set -g @catppuccin_window_current_background "default"
set -g @catppuccin_status_background "default"

set -g pane-border-lines heavy

# FORCE THE WINDOW NAME (Process name)
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"

# Load the theme file (Manual submodule path)
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# Status Bar Modules
set -g status-left ""
set -g status-right-length 100
set -g status-right ""
set -ag status-right "#{E:@catppuccin_status_session}"

# --- FZF Theme (Catppuccin Frappe) ---
set-environment -g FZF_DEFAULT_OPTS "\
--color=bg+:#363A4F,bg:#24273A,spinner:#F4DBD6,hl:#ED8796 \
--color=fg:#CAD3F5,header:#ED8796,info:#C6A0F6,pointer:#F4DBD6 \
--color=marker:#B7BDF8,fg+:#CAD3F5,prompt:#C6A0F6,hl+:#ED8796 \
--color=selected-bg:#494D64 \
--color=border:#6E738D,label:#CAD3F5"

# --- Session Manager (sesh + fzf) ---
bind-key "T" run-shell "sesh connect \"$(
  sesh list --icons | fzf-tmux -p 80%,70% \
    --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
    --header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list --icons)' \
    --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t --icons)' \
    --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c --icons)' \
    --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z --icons)' \
    --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list --icons)' \
    --preview-window 'right:55%' \
    --preview 'sesh preview {}'
)\""

## --- TPM Plugins ---
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.tmux/plugins/'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Initialize TPM (MUST BE AT THE BOTTOM)
run '~/.tmux/plugins/tpm/tpm'
